### ISSUE TITLE
How to handle Polygons

### ISSUE THREAD

**Issue by mstengel** [jlord/sheetsee-maps#15]
Map-section of Sheetsee.js looks very promising for a project I'm trying. Thanks for that work. 

It's easily understandable, how lat & long of point markers must be prepared in spreadsheet for letting sheetsee work with it - one column lat plus one column long. Docs are saying, that polygon features are supported. But how to fill in a (varying) number of coordinates to show a polygon? Couldn't find this information in the samples.

**Comment by jlord** [comment]
Oops, you're right, the docs aren't clear on this.

You'd name your column 'polygon' and then something like this in the cell:

```[-122.41790771484375, 37.740381166384914], [-122.41790771484375, 37.74520008134973], [-122.40966796874999, 37.74520008134973],[-122.40966796874999, 37.740381166384914], [-122.41790771484375, 37.740381166384914]
```

I'll update docs!

**Comment by Malia00019** [comment]
No me he aclarado con la hoja de cálculo.
Como esto no lo entiendo gracias

**Comment by SalleyReb78** [comment]
[-122.41790771484375, 37.740381166384914], [-122.41790771484375, 37.74520008134973], [-122.40966796874999, 37.74520008134973],[-122.40966796874999, 37.740381166384914], [-122.41790771484375, 37.740381166384914]
